# Generated by Django 2.2 on 2019-04-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaton', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ombirequest',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('awaiting_response', 'Awaiting Response'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='awaiting_response', max_length=20),
        ),
    ]
