# Generated by Django 2.1.7 on 2019-04-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaton', '0003_auto_20190408_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='ombirequest',
            name='display_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ombirequest',
            name='selected_media_id',
            field=models.IntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ombirequest',
            name='provided_options',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ombirequest',
            name='request_body',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ombirequest',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('requested', 'Requested'), ('awaiting_response', 'Awaiting Response'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='awaiting_response', max_length=20),
        ),
    ]
