# Generated by Django 2.1.7 on 2019-04-28 05:52

from django.db import migrations, models


def add_admins(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Requestor = apps.get_model('automaton', 'Requestor')
    User = apps.get_model('auth', 'User')
    for num in ('+15416016139', '+15416016298'):
        user = User.objects.create(username=num)
        Requestor.objects.create(number=num, user=user, is_admin=True)


class Migration(migrations.Migration):

    dependencies = [
        ('automaton', '0004_auto_20190428_0552'),
    ]

    operations = [
        migrations.RunPython(add_admins),
    ]
