# Generated by Django 2.2.28 on 2023-07-23 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automaton', '0005_admin_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_source', models.CharField(choices=[('ombi', 'Ombi'), ('readarr', 'Readarr')], max_length=50)),
                ('request_type', models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'TV Show'), ('audiobook', 'Audiobook'), ('choice', 'Choice'), ('unknown', 'Unknown')], max_length=50)),
                ('display_name', models.TextField(default=None, null=True)),
                ('request_body', models.TextField(default=None, null=True)),
                ('provided_options', models.TextField(default=None, null=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('requested', 'Requested'), ('awaiting_response', 'Awaiting Response'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='awaiting_response', max_length=20)),
                ('selected_media_id', models.IntegerField(db_index=True, default=None, null=True)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automaton.Requestor')),
            ],
        ),
        migrations.DeleteModel(
            name='OmbiRequest',
        ),
    ]
